version: '2'
services:
  piitrack-app:
    image: piitrack
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://piitrack-mssql:1433;database=PIITRACK
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  piitrack-mssql:
    extends:
      file: mssql.yml
      service: piitrack-mssql
